# Operator SDK Scorecard.
# See: https://git.io/Jv4ze

scorecard:
  output: json
  plugins:
    - basic:
        csv-path: "deploy/olm-catalog/ocean-operator/0.0.1/ocean-operator.v0.0.1.clusterserviceversion.yaml"
        cr-manifest:
          - "deploy/crds/ocean.spot.io_v1_cluster_cr.yaml"
          - "deploy/crds/ocean.spot.io_v1_launchspec_cr.yaml"
    - olm:
        csv-path: "deploy/olm-catalog/ocean-operator/0.0.1/ocean-operator.v0.0.1.clusterserviceversion.yaml"
        cr-manifest:
          - "deploy/crds/ocean.spot.io_v1_cluster_cr.yaml"
          - "deploy/crds/ocean.spot.io_v1_launchspec_cr.yaml"
