dist: build/_output

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - main: cmd/manager/main.go
    flags:
      - -mod=vendor
      - -trimpath
    ldflags:
      - -extldflags '-static' -s -w -X {{ .Env.VERSION_PKG }}.Version={{ .Env.VERSION_NUMBER }} -X {{ .Env.VERSION_PKG }}.Prerelease={{ .Env.VERSION_PRERELEASE }} -X {{ .Env.VERSION_PKG }}.Metadata={{ .Env.VERSION_BUILD_METADATA }}
    goos:
      - linux
    goarch:
      - amd64

archives:
  - name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}-{{ .Env.VERSION }}'
    files:
      - none*
