# permissions for end users to view oceancomponents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oceancomponent-viewer-role
rules:
- apiGroups:
  - ocean.spot.io
  resources:
  - oceancomponents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ocean.spot.io
  resources:
  - oceancomponents/status
  verbs:
  - get
