apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: launchspecs.ocean.spot.io
  annotations:
    helm.sh/hook: crd-install
spec:
  additionalPrinterColumns:
  - JSONPath: .status.launchSpecId
    description: The unique ID of the LaunchSpec
    name: Spec ID
    type: string
  - JSONPath: .spec.oceanId
    description: The unique ID of the Cluster
    name: Ocean ID
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: ocean.spot.io
  names:
    kind: LaunchSpec
    listKind: LaunchSpecList
    plural: launchspecs
    singular: launchspec
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: LaunchSpec allows you to configure a workload type for your Cluster.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Specification of the desired behavior of the LaunchSpec.
          properties:
            iamInstanceProfile:
              description: IAMInstanceProfile defines the desired state of IAMInstanceProfile.
              properties:
                arn:
                  type: string
                name:
                  type: string
              type: object
            imageId:
              type: string
            labels:
              items:
                description: Label defines the desired state of Label.
                properties:
                  key:
                    type: string
                  value:
                    type: string
                type: object
              type: array
            oceanId:
              type: string
            rootVolumeSize:
              type: integer
            securityGroupIds:
              items:
                type: string
              type: array
            subnetIds:
              items:
                type: string
              type: array
            taints:
              items:
                description: Taint defines the desired state of Taint.
                properties:
                  effect:
                    type: string
                  key:
                    type: string
                  value:
                    type: string
                type: object
              type: array
            userData:
              type: string
          type: object
        status:
          description: Most recently observed status of the LaunchSpec.
          properties:
            conditions:
              description: Represents the latest available observations of the current
                state.
              items:
                description: StatusCondition contains condition information.
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    format: date-time
                    type: string
                  lastUpdateTime:
                    description: The last time this condition was updated.
                    format: date-time
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Type of the condition.
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            details:
              description: Extended data associated with the status. This field is
                optional.
              properties:
                reconcileRequestUid:
                  description: Unique ID of the reconcile request.
                  type: string
              type: object
            launchSpecId:
              description: Unique ID of the LaunchSpec.
              type: string
            observedGeneration:
              description: The generation observed by the controller.
              format: int64
              type: integer
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
