apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocean-operator
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      name: ocean-operator
  template:
    metadata:
      labels:
        name: ocean-operator
    spec:
      serviceAccountName: ocean-operator
      containers:
      - name: ocean-operator
        image: spotinst/ocean-operator:0.0.1
        command:
        - ocean-operator
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: ocean-operator
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8380
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8380
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
