apiVersion: ocean.spot.io/v1alpha1
kind: OceanComponent
metadata:
  name: metrics-server
spec:
  type: Helm
  name: metrics-server
  url: https://charts.helm.sh/stable
  state: Present
  version: 2.8.8
